apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-radix
  labels:
    name: parsec-radix
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:splash2x_radix
        name: parsec-radix
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0 ./run -a run -S splash2x -p radix -i native -n 1"]
        resources:
          requests:
            cpu: "0.8"
          limits:
            cpu: "1.0"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-4core"
