apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-vips
  labels:
    name: parsec-vips
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_vips
        name: parsec-vips
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 1 ./run -a run -S parsec -p vips -i native -n 1"]
        resources:
          requests:
            cpu: "0.4"
          limits:
            cpu: "0.6"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-d-4core"
