apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-freqmine
  labels:
    name: parsec-freqmine
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_freqmine
        name: parsec-freqmine
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0,1,2,3 ./run -a run -S parsec -p freqmine -i native -n 4"]
        resources:
          requests:
            cpu: "2.7"
          limits:
            cpu: "4.0"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-d-4core"
