apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-vips
  labels:
    name: parsec-vips
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_vips
        name: parsec-vips
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 2,3 ./run -a run -S parsec -p vips -i native -n 2"]
        resources:
          requests:
            cpu: "1.8"
          limits:
            cpu: "2.0"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-4core"
