apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2025-04-17T22:20:25Z"
  name: part1.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    gceServiceAccount: default
  cloudControllerManager:
    image: gcr.io/k8s-staging-cloud-provider-gcp/cloud-controller-manager:master@sha256:e125f4e6792978125546e64279a13de18fdf6b704edfec8400cac1254d3adf88
  cloudProvider: gce
  configBase: gs://cca-self-work/part1.k8s.local
  containerRuntime: containerd
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-europe-west1-b
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-europe-west1-b
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.31.5
  masterPublicName: api.part1.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: cca-self-work
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.16.0/20
    name: europe-west1
    region: europe-west1
    type: Public
  topology:
    dns:
      type: None

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-04-17T22:20:26Z"
  labels:
    kops.k8s.io/cluster: part1.k8s.local
  name: master-europe-west1-b
spec:
  image: ubuntu-os-cloud/ubuntu-2404-noble-amd64-v20250130
  machineType: n2-standard-2
  maxSize: 1
  minSize: 1
  nodeLabels:
    cloud.google.com/metadata-proxy-ready: "true"
    kops.k8s.io/instancegroup: master-europe-west1-b
  role: Master
  subnets:
  - europe-west1
  zones:
  - europe-west1-b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-04-17T22:20:27Z"
  labels:
    kops.k8s.io/cluster: part1.k8s.local
  name: memcache-server
spec:
  image: ubuntu-os-cloud/ubuntu-2404-noble-amd64-v20250130
  machineType: n2-highcpu-2
  maxSize: 1
  minSize: 1
  nodeLabels:
    cca-project-nodetype: memcached
    cloud.google.com/metadata-proxy-ready: "true"
    kops.k8s.io/instancegroup: nodes-europe-west1-b
  role: Node
  subnets:
  - europe-west1
  zones:
  - europe-west1-b
