apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: parsec-dedup
  name: parsec-dedup
spec:
  template:
    spec:
      containers:
      - args:
        - -c
        - ./run -a run -S parsec -p dedup -i native -n 1
        command:
        - /bin/sh
        image: anakli/cca:parsec_dedup
        imagePullPolicy: Always
        name: parsec-dedup
        resources:
          requests:
            cpu: "333m"
          limits:
            cpu: "334m"
      nodeSelector:
        cca-project-nodetype: node-b
      restartPolicy: Never
